"""Catalogue d'icones pour les emplacements de l'ecran.

Chaque icone est un caractere Material Icons (police "gfonts://Material
Icons" embarquee dans firmware/package.yaml, avec un `glyphs:` limite a
exactement ce jeu). Les points de code viennent du fichier officiel
MaterialIcons-Regular.codepoints - ne pas en ajouter un nouveau ici sans
l'ajouter aussi au `glyphs:` du firmware, sinon il s'affichera comme une
case vide sur l'ecran.
"""

from __future__ import annotations

ICONS: dict[str, int] = {
    # Media / son
    "play_arrow": 0xE037,
    "pause": 0xE034,
    "stop": 0xE047,
    "skip_next": 0xE044,
    "skip_previous": 0xE045,
    "volume_up": 0xE050,
    "volume_down": 0xE04D,
    "volume_off": 0xE04F,
    "volume_mute": 0xE04E,
    "mic": 0xE029,
    "mic_off": 0xE02B,
    "speaker": 0xE32D,
    "speaker_group": 0xE32E,
    "headset": 0xE310,
    "headset_mic": 0xE311,
    "headphones": 0xF01F,
    "radio": 0xE03E,
    "music_note": 0xE405,
    "cast": 0xE307,
    "videocam": 0xE04B,
    "camera_alt": 0xE3B0,
    "photo_camera": 0xE412,
    "tv": 0xE333,

    # Maison / eclairage / confort
    "home": 0xE88A,
    "lightbulb_outline": 0xE90F,
    "wb_incandescent": 0xE42E,
    "wb_iridescent": 0xE436,
    "light_mode": 0xE518,
    "dark_mode": 0xE51C,
    "brightness_high": 0xE1AC,
    "brightness_medium": 0xE1AE,
    "brightness_low": 0xE1AD,
    "nightlight_round": 0xEF5E,
    "power_settings_new": 0xE8AC,
    "power": 0xE63C,
    "power_off": 0xE646,
    "outlet": 0xF1D4,
    "electrical_services": 0xF102,
    "flash_on": 0xE3E7,
    "flash_off": 0xE3E6,
    "garage": 0xF011,
    "door_sliding": 0xEFFE,
    "sensor_door": 0xF1B5,
    "sensor_window": 0xF1B4,
    "window": 0xF088,
    "blinds": 0xE286,
    "curtains": 0xEC1E,
    "roofing": 0xF201,
    "weekend": 0xE16B,
    "chair": 0xEFED,
    "kitchen": 0xEB47,
    "countertops": 0xF1F7,
    "local_laundry_service": 0xE54A,
    "dry_cleaning": 0xEA58,
    "bathtub": 0xEA41,
    "shower": 0xF061,
    "deck": 0xEA42,
    "yard": 0xF089,
    "grass": 0xF205,
    "outdoor_grill": 0xEA47,
    "fireplace": 0xEA43,
    "hot_tub": 0xEB46,
    "pool": 0xEB48,

    # Climat / meteo
    "ac_unit": 0xEB3B,
    "thermostat": 0xF076,
    "device_thermostat": 0xE1FF,
    "wb_sunny": 0xE430,
    "wb_cloudy": 0xE42D,
    "wb_twilight": 0xE1C6,
    "cloud": 0xE2BD,
    "cloud_off": 0xE2C1,
    "thunderstorm": 0xEBDB,
    "grain": 0xE3EA,
    "water_drop": 0xE798,
    "water": 0xF084,
    "opacity": 0xE91C,
    "air": 0xEFD8,
    "waves": 0xE176,
    "umbrella": 0xF1AD,
    "eco": 0xEA35,
    "park": 0xEA63,
    "local_florist": 0xE545,

    # Reseau / connectivite
    "wifi": 0xE63E,
    "wifi_off": 0xE648,
    "signal_wifi_4_bar": 0xE1D8,
    "bluetooth": 0xE1A7,
    "bluetooth_connected": 0xE1A8,
    "bluetooth_disabled": 0xE1A9,
    "router": 0xE328,
    "network_check": 0xE640,
    "signal_cellular_alt": 0xE202,
    "sync": 0xE627,
    "refresh": 0xE5D5,

    # Informatique / peripheriques
    "computer": 0xE30A,
    "desktop_windows": 0xE30C,
    "desktop_mac": 0xE30B,
    "laptop": 0xE31E,
    "laptop_mac": 0xE320,
    "keyboard": 0xE312,
    "mouse": 0xE323,
    "print": 0xE8AD,
    "scanner": 0xE329,
    "usb": 0xE1E0,
    "sd_card": 0xE623,
    "sim_card": 0xE32B,
    "memory": 0xE322,
    "storage": 0xE1DB,
    "developer_board": 0xE30D,
    "smart_toy": 0xF06C,
    "phone_iphone": 0xE325,
    "smartphone": 0xE32C,
    "tablet_mac": 0xE331,
    "watch": 0xE334,
    "battery_full": 0xE1A4,
    "battery_charging_full": 0xE1A3,
    "battery_alert": 0xE19C,
    "battery_std": 0xE1A5,
    "battery_unknown": 0xE1A6,
    "data_usage": 0xE1AF,
    "speed": 0xE9E4,
    "tune": 0xE429,

    # Securite
    "lock": 0xE897,
    "lock_open": 0xE898,
    "security": 0xE32A,
    "shield": 0xE9E0,
    "vpn_key": 0xE0DA,
    "key": 0xE73C,
    "fingerprint": 0xE90D,

    # Transport
    "directions_car": 0xE531,
    "electric_car": 0xEB1C,
    "ev_station": 0xE56D,
    "local_gas_station": 0xE546,
    "pedal_bike": 0xEB29,
    "directions_walk": 0xE536,

    # Loisirs
    "sports_esports": 0xEA28,
    "videogame_asset": 0xE338,
    "restaurant": 0xE56C,
    "local_cafe": 0xE541,
    "book": 0xE865,
    "pets": 0xE91D,

    # Bricolage / entretien
    "build": 0xE869,
    "handyman": 0xF10B,
    "construction": 0xEA3C,
    "plumbing": 0xF107,

    # Temps / rappels
    "timer": 0xE425,
    "alarm": 0xE855,
    "schedule": 0xE8B5,
    "today": 0xE8DF,
    "event": 0xE878,
    "calendar_today": 0xE935,

    # Interface generique
    "settings": 0xE8B8,
    "notifications": 0xE7F4,
    "star": 0xE838,
    "favorite": 0xE87D,
    "info": 0xE88E,
    "warning": 0xE002,
    "error": 0xE000,
    "check_circle": 0xE86C,
    "cancel": 0xE5C9,
    "add": 0xE145,
    "remove": 0xE15B,
    "edit": 0xE3C9,
    "delete": 0xE872,
    "search": 0xE8B6,
    "shopping_cart": 0xE8CC,
    "work": 0xE8F9,
    "arrow_upward": 0xE5D8,
    "arrow_downward": 0xE5DB,
    "chevron_left": 0xE5CB,
    "chevron_right": 0xE5CC,
    "expand_more": 0xE5CF,
    "expand_less": 0xE5CE,
}

# Libelles humains affiches dans le selecteur d'icone de l'appli PC.
ICON_LABELS: dict[str, str] = {
    "play_arrow": "Lecture",
    "pause": "Pause",
    "stop": "Stop",
    "skip_next": "Suivant",
    "skip_previous": "Precedent",
    "volume_up": "Volume +",
    "volume_down": "Volume -",
    "volume_off": "Muet",
    "volume_mute": "Son coupe",
    "mic": "Micro",
    "mic_off": "Micro coupe",
    "speaker": "Enceinte",
    "speaker_group": "Enceintes",
    "headset": "Casque",
    "headset_mic": "Casque-micro",
    "headphones": "Ecouteurs",
    "radio": "Radio",
    "music_note": "Musique",
    "cast": "Diffuser (cast)",
    "videocam": "Camera",
    "camera_alt": "Appareil photo",
    "photo_camera": "Photo",
    "tv": "TV",

    "home": "Maison",
    "lightbulb_outline": "Lumiere",
    "wb_incandescent": "Ampoule (chaude)",
    "wb_iridescent": "Ampoule (froide)",
    "light_mode": "Mode jour",
    "dark_mode": "Mode nuit",
    "brightness_high": "Luminosite forte",
    "brightness_medium": "Luminosite moyenne",
    "brightness_low": "Luminosite faible",
    "nightlight_round": "Veilleuse",
    "power_settings_new": "Marche/arret",
    "power": "Marche",
    "power_off": "Arret",
    "outlet": "Prise electrique",
    "electrical_services": "Electricite",
    "flash_on": "Flash on",
    "flash_off": "Flash off",
    "garage": "Garage",
    "door_sliding": "Porte coulissante",
    "sensor_door": "Capteur de porte",
    "sensor_window": "Capteur de fenetre",
    "window": "Fenetre",
    "blinds": "Volets",
    "curtains": "Rideaux",
    "roofing": "Toiture",
    "weekend": "Canape",
    "chair": "Chaise",
    "kitchen": "Cuisine",
    "countertops": "Plan de travail",
    "local_laundry_service": "Lave-linge",
    "dry_cleaning": "Pressing",
    "bathtub": "Baignoire",
    "shower": "Douche",
    "deck": "Terrasse",
    "yard": "Jardin",
    "grass": "Pelouse",
    "outdoor_grill": "Barbecue",
    "fireplace": "Cheminee",
    "hot_tub": "Jacuzzi",
    "pool": "Piscine",

    "ac_unit": "Froid / clim",
    "thermostat": "Temperature",
    "device_thermostat": "Thermostat",
    "wb_sunny": "Meteo / soleil",
    "wb_cloudy": "Nuageux",
    "wb_twilight": "Crepuscule",
    "cloud": "Nuage",
    "cloud_off": "Hors ligne (nuage)",
    "thunderstorm": "Orage",
    "grain": "Bruine",
    "water_drop": "Goutte d'eau",
    "water": "Eau",
    "opacity": "Humidite",
    "air": "Air",
    "waves": "Vagues",
    "umbrella": "Parapluie",
    "eco": "Ecologie",
    "park": "Parc",
    "local_florist": "Fleurs",

    "wifi": "Wifi",
    "wifi_off": "Wifi coupe",
    "signal_wifi_4_bar": "Signal wifi",
    "bluetooth": "Bluetooth",
    "bluetooth_connected": "Bluetooth connecte",
    "bluetooth_disabled": "Bluetooth desactive",
    "router": "Routeur",
    "network_check": "Reseau",
    "signal_cellular_alt": "Signal mobile",
    "sync": "Synchroniser",
    "refresh": "Rafraichir",

    "computer": "Ordinateur",
    "desktop_windows": "PC de bureau",
    "desktop_mac": "Mac de bureau",
    "laptop": "Ordinateur portable",
    "laptop_mac": "Mac portable",
    "keyboard": "Clavier",
    "mouse": "Souris",
    "print": "Imprimante",
    "scanner": "Scanner",
    "usb": "USB",
    "sd_card": "Carte SD",
    "sim_card": "Carte SIM",
    "memory": "Memoire",
    "storage": "Stockage",
    "developer_board": "Carte electronique",
    "smart_toy": "Robot",
    "phone_iphone": "Telephone",
    "smartphone": "Smartphone",
    "tablet_mac": "Tablette",
    "watch": "Montre",
    "battery_full": "Batterie pleine",
    "battery_charging_full": "Batterie en charge",
    "battery_alert": "Batterie faible",
    "battery_std": "Batterie",
    "battery_unknown": "Batterie inconnue",
    "data_usage": "Donnees",
    "speed": "Vitesse",
    "tune": "Reglages fins",

    "lock": "Verrou",
    "lock_open": "Deverrouille",
    "security": "Securite",
    "shield": "Bouclier",
    "vpn_key": "Cle VPN",
    "key": "Cle",
    "fingerprint": "Empreinte",

    "directions_car": "Voiture",
    "electric_car": "Voiture electrique",
    "ev_station": "Borne electrique",
    "local_gas_station": "Station essence",
    "pedal_bike": "Velo",
    "directions_walk": "Marche a pied",

    "sports_esports": "Jeu video",
    "videogame_asset": "Manette",
    "restaurant": "Restaurant",
    "local_cafe": "Cafe",
    "book": "Livre",
    "pets": "Animaux",

    "build": "Outils",
    "handyman": "Bricolage",
    "construction": "Travaux",
    "plumbing": "Plomberie",

    "timer": "Minuteur",
    "alarm": "Alarme",
    "schedule": "Horaire",
    "today": "Aujourd'hui",
    "event": "Evenement",
    "calendar_today": "Calendrier",

    "settings": "Parametres",
    "notifications": "Notification",
    "star": "Favori",
    "favorite": "Coeur",
    "info": "Info",
    "warning": "Avertissement",
    "error": "Erreur",
    "check_circle": "Valide",
    "cancel": "Annuler",
    "add": "Ajouter",
    "remove": "Retirer",
    "edit": "Modifier",
    "delete": "Supprimer",
    "search": "Rechercher",
    "shopping_cart": "Panier",
    "work": "Travail",
    "arrow_upward": "Fleche haut",
    "arrow_downward": "Fleche bas",
    "chevron_left": "Fleche gauche",
    "chevron_right": "Fleche droite",
    "expand_more": "Deplier",
    "expand_less": "Replier",
}


def icon_char(icon_key: str) -> str:
    """Caractere UTF-8 a pousser vers l'entite 'Slot N - icone' du firmware."""
    codepoint = ICONS.get(icon_key)
    return chr(codepoint) if codepoint is not None else ""


def icon_choices() -> list[dict[str, str]]:
    """Liste [{key, label, char}] pour le selecteur d'icone de l'appli PC."""
    return [
        {"key": key, "label": ICON_LABELS.get(key, key), "char": icon_char(key)}
        for key in ICONS
    ]
